svn checkout http://svn.maarch.org/maarch_entreprise/branches/1.6          apps/maarch_entreprise
svn checkout http://svn.maarch.org/attachments/branches/1.6                modules/attachments
svn checkout http://svn.maarch.org/avis/branches/1.6                       modules/avis
svn checkout http://svn.maarch.org/basket/branches/1.6                     modules/basket
svn checkout http://svn.maarch.org/cases/branches/1.6                      modules/cases
svn checkout http://svn.maarch.org/content_management/branches/1.6         modules/content_management
svn checkout http://svn.maarch.org/entities/branches/1.6                   modules/entities
svn checkout http://svn.maarch.org/fileplan/branches/1.6                   modules/fileplan
svn checkout http://svn.maarch.org/folder/branches/1.6                     modules/folder
svn checkout http://svn.maarch.org/full_text/branches/1.6                  modules/full_text
svn checkout http://svn.maarch.org/ldap/branches/1.6                       modules/ldap
svn checkout http://svn.maarch.org/life_cycle/branches/1.6                 modules/life_cycle
svn checkout http://svn.maarch.org/notes/branches/1.6                      modules/notes
svn checkout http://svn.maarch.org/notifications/branches/1.6              modules/notifications
svn checkout http://svn.maarch.org/reports/branches/1.6                    modules/reports
svn checkout http://svn.maarch.org/sendmail/branches/1.6                   modules/sendmail
svn checkout http://svn.maarch.org/tags/branches/1.6                       modules/tags
svn checkout http://svn.maarch.org/templates/branches/1.6                  modules/templates
svn checkout http://svn.maarch.org/thesaurus/branches/1.6                  modules/thesaurus
svn checkout http://svn.maarch.org/thumbnails/branches/1.6                 modules/thumbnails
svn checkout http://svn.maarch.org/visa/branches/1.6                       modules/visa
