--------------------------------------------------------
--  DDL for Table ACTIONS
--------------------------------------------------------

  CREATE TABLE "ACTIONS"
   (    "ID" NUMBER NOT NULL ENABLE,
    "KEYWORD" VARCHAR2(32 CHAR) DEFAULT NULL,
    "LABEL_ACTION" VARCHAR2(255 CHAR),
    "ID_STATUS" VARCHAR2(10 CHAR),
    "IS_SYSTEM" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
    "ENABLED" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTION_PAGE" VARCHAR2(255 CHAR),
    "HISTORY" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
    "ORIGIN" VARCHAR2(255 CHAR) DEFAULT 'apps' NOT NULL ENABLE,
    "CREATE_ID" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
     CONSTRAINT "ACTIONS_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

  CREATE TABLE "DOCSERVERS"
   (    "DOCSERVER_ID" VARCHAR2(32) DEFAULT '1',
    "DEVICE_TYPE" VARCHAR2(32) DEFAULT NULL,
    "DEVICE_LABEL" VARCHAR2(255) DEFAULT NULL,
    "IS_READONLY" VARCHAR2(1) DEFAULT 'N',
    "ENABLED" VARCHAR2(1) DEFAULT 'Y',
    "SIZE_LIMIT" NUMBER DEFAULT '0',
    "ACTUAL_SIZE" NUMBER DEFAULT '0',
    "PATH_TEMPLATE" VARCHAR2(255) NOT NULL ENABLE,
    "EXT_DOCSERVER_INFO" VARCHAR2(255) DEFAULT NULL,
    "CHAIN_BEFORE" VARCHAR2(32) DEFAULT NULL,
    "CHAIN_AFTER" VARCHAR2(32) DEFAULT NULL,
    "CREATION_DATE" DATE DEFAULT sysdate,
    "CLOSING_DATE" DATE DEFAULT sysdate,
    "COLL_ID" VARCHAR2(32) NOT NULL ENABLE,
    "PRIORITY" NUMBER DEFAULT '10',
     PRIMARY KEY ("DOCSERVER_ID") ENABLE
   ) ;


--------------------------------------------------------
--  DDL for Table DOCTYPES
--------------------------------------------------------

  CREATE TABLE "DOCTYPES"
   (    "COLL_ID" VARCHAR2(32) DEFAULT '',
    "TYPE_ID" NUMBER NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(255) DEFAULT '',
    "ENABLED" VARCHAR2(1) DEFAULT 'Y',
    "DOCTYPES_FIRST_LEVEL_ID" NUMBER DEFAULT NULL,
    "DOCTYPES_SECOND_LEVEL_ID" NUMBER DEFAULT NULL,
    "PRIMARY_RETENTION" VARCHAR2(50) DEFAULT NULL,
    "SECONDARY_RETENTION" VARCHAR2(50) DEFAULT NULL,
     PRIMARY KEY ("TYPE_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table EXT_DOCSERVER
--------------------------------------------------------

  CREATE TABLE "EXT_DOCSERVER"
   (    "DOC_ID" VARCHAR2(255),
    "PATH" VARCHAR2(255)
   ) ;


--------------------------------------------------------
--  DDL for Table GROUPSECURITY
--------------------------------------------------------

  CREATE TABLE "GROUPSECURITY"
   (    "GROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "RESGROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "CAN_VIEW" VARCHAR2(1) NOT NULL ENABLE,
    "CAN_ADD" VARCHAR2(1) NOT NULL ENABLE,
    "CAN_DELETE" VARCHAR2(1) NOT NULL ENABLE,
     PRIMARY KEY ("GROUP_ID", "RESGROUP_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
    "TABLE_NAME" VARCHAR2(32) DEFAULT NULL,
    "RECORD_ID" VARCHAR2(255) DEFAULT NULL,
    "EVENT_TYPE" VARCHAR2(32) NOT NULL ENABLE,
    "USER_ID" VARCHAR2(50) NOT NULL ENABLE,
    "EVENT_DATE" DATE DEFAULT sysdate,
    "INFO" VARCHAR2(1000),
    "ID_MODULE" VARCHAR2(50) DEFAULT 'admin',
    "REMOTE_IP" VARCHAR2(50) DEFAULT NULL,
     PRIMARY KEY ("ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table HISTORY_BATCH
--------------------------------------------------------

  CREATE TABLE "HISTORY_BATCH"
   (    "ID" NUMBER NOT NULL ENABLE,
    "MODULE_NAME" VARCHAR2(32) DEFAULT NULL,
    "BATCH_ID"  NUMBER DEFAULT NULL,
    "EVENT_DATE" DATE DEFAULT sysdate,
    "TOTAL_PROCESSED" NUMBER NOT NULL ENABLE,
    "TOTAL_ERRORS" NUMBER NOT NULL ENABLE,
    "INFO" VARCHAR2(1000),
     PRIMARY KEY ("ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table PARAMETERS
--------------------------------------------------------

  CREATE TABLE "PARAMETERS"
   (    "ID" VARCHAR2(50) NOT NULL ENABLE,
    "PARAM_VALUE_STRING" VARCHAR2(50) DEFAULT NULL,
    "PARAM_VALUE_INT" NUMBER DEFAULT NULL,
    "PARAM_VALUE_DATE" DATE DEFAULT NULL,
     PRIMARY KEY ("ID") ENABLE
   ) ;


--------------------------------------------------------
--  DDL for Table RESGROUP_CONTENT
--------------------------------------------------------

  CREATE TABLE "RESGROUP_CONTENT"
   (    "COLL_ID" VARCHAR2(8) NOT NULL ENABLE,
    "RES_ID" NUMBER NOT NULL ENABLE,
    "RESGROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "SEQUENCE" NUMBER NOT NULL ENABLE,
     PRIMARY KEY ("COLL_ID", "RES_ID", "RESGROUP_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table RESGROUPS
--------------------------------------------------------

  CREATE TABLE "RESGROUPS"
   (    "RESGROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "RESGROUP_DESC" VARCHAR2(255) NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
    "CREATION_DATE" DATE DEFAULT sysdate,
     PRIMARY KEY ("RESGROUP_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table SECURITY
--------------------------------------------------------

  CREATE TABLE "SECURITY"
   (    "SECURITY_ID" NUMBER NOT NULL ENABLE,
    "GROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "COLL_ID" VARCHAR2(32) NOT NULL ENABLE,
    "WHERE_CLAUSE" VARCHAR2(255) DEFAULT NULL,
    "MAARCH_COMMENT" VARCHAR2(1000),
    "CAN_INSERT" VARCHAR2(1) DEFAULT 'N',
    "CAN_UPDATE" VARCHAR2(1) DEFAULT 'N',
    "CAN_DELETE" VARCHAR2(1) DEFAULT 'N',
    "RIGHTS_BITMASK" NUMBER NOT NULL,
    "MR_START_DATE" DATE DEFAULT NULL,
    "MR_STOP_DATE" DATE DEFAULT NULL,
    "WHERE_TARGET" VARCHAR2(15) DEFAULT 'DOC',
     PRIMARY KEY ("SECURIY_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "STATUS"
   (    "ID" VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "LABEL_STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "IS_SYSTEM" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL ENABLE,
    "IMG_FILENAME" VARCHAR2(255 CHAR),
    "MAARCH_MODULE" VARCHAR2(255 CHAR) DEFAULT 'apps' NOT NULL ENABLE,
    "CAN_BE_SEARCHED" VARCHAR2(1 CHAR) DEFAULT 'Y',
     CONSTRAINT "STATUS_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table USERGROUP_CONTENT
--------------------------------------------------------

  CREATE TABLE "USERGROUP_CONTENT"
   (    "USER_ID" VARCHAR2(32) NOT NULL ENABLE,
    "GROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "PRIMARY_GROUP" VARCHAR2(1) NOT NULL ENABLE,
    "ROLE" VARCHAR2(255) DEFAULT NULL,
     PRIMARY KEY ("USER_ID", "GROUP_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table USERGROUPS
--------------------------------------------------------

  CREATE TABLE "USERGROUPS"
   (    "GROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "GROUP_DESC" VARCHAR2(255) DEFAULT NULL,
    "ADMINISTRATOR" VARCHAR2(1) DEFAULT 'N',
    "CUSTOM_RIGHT1" VARCHAR2(1) DEFAULT 'N',
    "CUSTOM_RIGHT2" VARCHAR2(1) DEFAULT 'N',
    "CUSTOM_RIGHT3" VARCHAR2(1) DEFAULT 'N',
    "CUSTOM_RIGHT4" VARCHAR2(1) DEFAULT 'N',
    "ENABLED" VARCHAR2(1) DEFAULT 'Y',
     PRIMARY KEY ("GROUP_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table USERGROUPS_SERVICES
--------------------------------------------------------

  CREATE TABLE "USERGROUPS_SERVICES"
   (    "GROUP_ID" VARCHAR2(32) NOT NULL ENABLE,
    "SERVICE_ID" VARCHAR2(32) NOT NULL ENABLE,
     PRIMARY KEY ("GROUP_ID", "SERVICE_ID") ENABLE
   ) ;

--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

  CREATE TABLE "USERS"
   (    "USER_ID" VARCHAR2(32) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(255) DEFAULT NULL,
    "FIRSTNAME" VARCHAR2(255) DEFAULT NULL,
    "LASTNAME" VARCHAR2(255) DEFAULT NULL,
    "PHONE" VARCHAR2(15) DEFAULT NULL,
    "MAIL" VARCHAR2(255) DEFAULT NULL,
    "DEPARTMENT" VARCHAR2(50) DEFAULT NULL,
    "CUSTOM_T1" VARCHAR2(50) DEFAULT NULL,
    "CUSTOM_T2" VARCHAR2(50) DEFAULT NULL,
    "CUSTOM_T3" VARCHAR2(50) DEFAULT NULL,
    "COOKIE_KEY" VARCHAR2(255) DEFAULT NULL,
    "COOKIE_DATE" DATE DEFAULT sysdate,
    "ENABLED" VARCHAR2(1) DEFAULT 'Y',
    "CHANGE_PASSWORD" VARCHAR2(1) DEFAULT 'Y',
    "DELAY_NUMBER" NUMBER DEFAULT NULL,
    "STATUS" VARCHAR2(10) DEFAULT 'OK',
    "LOGINMODE" VARCHAR2(50) DEFAULT NULL,

     PRIMARY KEY ("USER_ID") ENABLE
   ) ;


--------------------------------------------------------
--  SEQUENCES AND TRIGGERS
--------------------------------------------------------

 CREATE SEQUENCE  "SEQ_ACTIONS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 create or replace TRIGGER TRG_ACTIONS
 BEFORE INSERT ON ACTIONS
FOR EACH ROW
BEGIN
  SELECT SEQ_ACTIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

 CREATE SEQUENCE  "SEQ_DOCTYPES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 create or replace TRIGGER TRG_DOCTYPES
 BEFORE INSERT ON DOCTYPES
FOR EACH ROW
BEGIN
  SELECT SEQ_DOCTYPES.NEXTVAL INTO :NEW.TYPE_ID FROM DUAL;
END;
/

 CREATE SEQUENCE  "SEQ_HISTORY"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 create or replace TRIGGER TRG_HISTORY
 BEFORE INSERT ON HISTORY
FOR EACH ROW
BEGIN
  SELECT SEQ_HISTORY.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

 CREATE SEQUENCE  "SEQ_SECURITY"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 20 CACHE 20 NOORDER  NOCYCLE ;
 create or replace TRIGGER TRG_SECURITY
 BEFORE INSERT ON SECURITY
FOR EACH ROW
BEGIN
  SELECT SEQ_SECURITY.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

 CREATE SEQUENCE  "SEQ_HISTORY_BATCH"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 create or replace TRIGGER TRG_HISTORY_BATCH
 BEFORE INSERT ON HISTORY_BATCH
FOR EACH ROW
BEGIN
  SELECT SEQ_HISTORY_BATCH.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

