
CREATE TABLE USERGROUPS_REPORTS
(
  GROUP_ID   VARCHAR2(32 BYTE)                  NOT NULL,
  REPORT_ID  VARCHAR2(50 BYTE)                  NOT NULL
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE USERGROUPS_REPORTS ADD (
  CONSTRAINT USERGROUPS_REPORTS_PKEY
 PRIMARY KEY
 (GROUP_ID, REPORT_ID));