CREATE TABLE res_attachments
(
  res_id bigint NOT NULL auto_increment,
  title varchar(255) DEFAULT NULL,
  subject text,
  description text,
  publisher varchar(255) DEFAULT NULL,
  contributor varchar(255) DEFAULT NULL,
  type_id bigint,
  format varchar(50) NOT NULL,
  typist varchar(50) NOT NULL,
  creation_date datetime NOT NULL,
  fulltext_result varchar(10) DEFAULT NULL,
  ocr_result varchar(10) DEFAULT NULL,
  author varchar(255) DEFAULT NULL,
  author_name text,
  identifier varchar(255) DEFAULT NULL,
  source varchar(255) DEFAULT NULL,
  doc_language varchar(50) DEFAULT NULL,
  relation bigint,
  coverage varchar(255) DEFAULT NULL,
  doc_date datetime,
  docserver_id varchar(32) NOT NULL,
  folders_system_id bigint,
  arbox_id varchar(32) DEFAULT NULL,
  path varchar(255) DEFAULT NULL,
  filename varchar(255) DEFAULT NULL,
  offset_doc varchar(255) DEFAULT NULL,
  logical_adr varchar(255) DEFAULT NULL,
  fingerprint varchar(255) DEFAULT NULL,
  filesize bigint,
  is_paper char(1) DEFAULT NULL,
  page_count integer,
  scan_date datetime,
  scan_user varchar(50) DEFAULT NULL,
  scan_location varchar(255) DEFAULT NULL,
  scan_wkstation varchar(255) DEFAULT NULL,
  scan_batch varchar(50) DEFAULT NULL,
  burn_batch varchar(50) DEFAULT NULL,
  scan_postmark varchar(50) DEFAULT NULL,
  envelop_id bigint,
  status varchar(10) DEFAULT NULL,
  destination varchar(50) DEFAULT NULL,
  approver varchar(50) DEFAULT NULL,
  validation_date datetime,
  work_batch bigint,
  origin varchar(50) DEFAULT NULL,
  is_ingoing char(1) DEFAULT NULL,
  priority smallint,
  initiator varchar(50) DEFAULT NULL,
  dest_user varchar(50) DEFAULT NULL,
  coll_id varchar(32) NOT NULL ,
  res_id_master bigint,
 PRIMARY KEY (res_id)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
